version: '3'

services:
  hadoop-master:
    build:
      context: .
      dockerfile: docker/hadoop-master/Dockerfile
    container_name: hadoop-master
    hostname: hadoop-master
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9870:9870"  # Hadoop NameNode web UI
      - "8088:8088"  # ResourceManager web UI
    volumes:
      - ./hadoop_data/namenode:/opt/hadoop/dfs/name
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    networks:
      - hadoop_network

  hadoop-worker1:
    build:
      context: .
      dockerfile: docker/hadoop-worker/Dockerfile
    container_name: hadoop-worker1
    hostname: hadoop-worker1
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./hadoop_data/datanode1:/opt/hadoop/dfs/data
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    depends_on:
      - hadoop-master
    networks:
      - hadoop_network

  hadoop-worker2:
    build:
      context: .
      dockerfile: docker/hadoop-worker/Dockerfile
    container_name: hadoop-worker2
    hostname: hadoop-worker2
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./hadoop_data/datanode2:/opt/hadoop/dfs/data
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    depends_on:
      - hadoop-master
    networks:
      - hadoop_network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ulimits:
      nofile:
        soft: 65536
        hard: 65536    
    ports:
      - "2181:2181"
    networks:
      - hadoop_network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "reddit_posts:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper
    networks:
      - hadoop_network

  hbase:
    image: harisekhon/hbase
    container_name: hbase
    ports:
      - "16010:16010"
      - "9090:9090"
      - "16000:16000"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      HBASE_MANAGES_ZK: "false"
      HBASE_ZOOKEEPER_QUORUM: localhost
    depends_on:
      - hadoop-master
      - zookeeper
    networks:
      - hadoop_network

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - hadoop_network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    networks:
      - hadoop_network

networks:
  hadoop_network:
    driver: bridge